# -*- coding: utf-8 -*-
"""HW0223.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RHh6VdOlUXOF2gM5OXPmxLNPYB6dJo3F
"""

import numpy as np
import matplotlib.pyplot as plt

def normal_pdf(x, mu, sigma):
    return (1.0 / (sigma * np.sqrt(2*np.pi))) * np.exp(-0.5 * ((x - mu) / sigma)**2)

def simulate_sample_means(dist, n, m, rng, **kwargs):
    if dist == "bernoulli":
        p = kwargs["p"]
        samples = rng.binomial(1, p, size=(m, n))
        return samples.mean(axis=1)

    if dist == "exponential":
        lam = kwargs["lam"]
        samples = rng.exponential(scale=1.0/lam, size=(m, n))
        return samples.mean(axis=1)

def plot_clt_demo(
    p=0.3,
    lam=2.0,
    ns=(1, 5, 30, 100),
    m=20000,
    bins=40,
    seed=42,
    out_path="clt_demo.png",
):
    rng = np.random.default_rng(seed)

    fig, axes = plt.subplots(2, 4, figsize=(18, 6), constrained_layout=True)

    # ---- Bernoulli ----
    mu_b = p
    var_b = p * (1 - p)

    for j, n in enumerate(ns):
        ax = axes[0, j]
        means = simulate_sample_means("bernoulli", n, m, rng, p=p)

        ax.hist(means, bins=bins, density=True, alpha=0.65)

        sigma = np.sqrt(var_b / n)
        x = np.linspace(max(0, mu_b - 4*sigma), min(1, mu_b + 4*sigma), 400)
        ax.plot(x, normal_pdf(x, mu_b, sigma), linewidth=2)

        ax.set_title(f"Bernoulli n={n}")
        ax.set_xlabel("Sample mean")
        if j == 0:
            ax.set_ylabel("Density")

    # ---- Exponential ----
    mu_e = 1/lam
    var_e = 1/(lam**2)

    for j, n in enumerate(ns):
        ax = axes[1, j]
        means = simulate_sample_means("exponential", n, m, rng, lam=lam)

        ax.hist(means, bins=bins, density=True, alpha=0.65)

        sigma = np.sqrt(var_e / n)
        x = np.linspace(np.percentile(means, 0.5), np.percentile(means, 99.5), 400)
        ax.plot(x, normal_pdf(x, mu_e, sigma), linewidth=2)

        ax.set_title(f"Exp n={n}")
        ax.set_xlabel("Sample mean")
        if j == 0:
            ax.set_ylabel("Density")

    fig.suptitle(f"Central Limit Theorem — Bernoulli(p={p}) & Exp(λ={lam})")

    # ✔ 存圖
    fig.savefig(out_path, dpi=200)

    # ✔ 顯示圖
    plt.show()


if __name__ == "__main__":
    plot_clt_demo()